on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - gatsby/**
  pull_request:
    branches:
      - master
      - dev

env:
  WORKING_DIRECTORY: ./functions

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: npm run lint
        working-directory: ${{ env.WORKING_DIRECTORY }}

  deploy:
    if: github.event_name	== 'push'
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: cp data functions/data
      - name: Deploy to Prod Firebase Functions
        if: github.ref == 'refs/heads/master'
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
      - name: Deploy to Stg Firebase Functions
        if: github.ref == 'refs/heads/dev'
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID_STG }}
