on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - functions/**
      - "*"
      - "!firebase.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prettier check gatsby
        run: |
          cd gatsby
          npm ci
          npx prettier --check

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Build gatsby
        run: |
          cd gatsby
          npm ci
          npm run build
          mv public ../public
      - name: Deploy to Prod Firebase Hosting
        if: github.ref == 'refs/heads/master'
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
      - name: Deploy to Stg Firebase Hosting
        if: github.ref == 'refs/heads/dev'
        uses: w9jds/firebase-action@v1.1.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID_STG }}
